const CONTACT_FORM_ACTIONS_TYPES = {
    SUBMIT_CONTACT_FORM:'SUBMIT_CONTACT_FORM',
};
const MEMBERS_ACTIONS_TYPES = {
    ADD_MEMBERS_TO_STATE:'ADD_MEMBERS_TO_STATE',
};

export {
    CONTACT_FORM_ACTIONS_TYPES,
    MEMBERS_ACTIONS_TYPES
};

